- name: Setup ansible controller
  hosts: localhost
  connection: local
  become: True
  vars:
    ansible_user: 'rnd'
  tasks:
    - include_tasks: 'tasks/requirement.yml'
    - include_tasks: 'tasks/vim.yml'
