---
- name: Make dir highlights
  shell: 'mkdir -p /home/{{ ansible_user }}/.vim/autoload /home/{{ ansible_user }}/.vim/bundle'

- name: Download pathogen.vim
  shell: 'curl -fLo /home/{{ ansible_user }}/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim'

- name: Git clone vim-ansible-yaml
  git:
    repo: https://github.com/chase/vim-ansible-yaml.git
    dest: /home/{{ ansible_user }}/.vim/bundle/vim-ansible-yaml

- name: Configure vimrc
  lineinfile:
    path: /home/{{ ansible_user }}/.vimrc
    line: '{{ item }}'
  with_items:
    - 'set number'
    - 'execute pathogen#infect()'
    - 'syntax on'
    - 'set smartindent'
    - 'set tabstop=2'
    - 'set expandtab'
    - 'set shiftwidth=2'

- name: Configure Bashrc
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: '{{ item }}'
  with_items:
    - "alias ans='ansible'"
    - "alias anp='ansible-playbook'"
