# --- # Start Play Book

# SSH Auto Pass 적용
- name: Create authority between server and nodes
  hosts: nodes
  connection: local
  become: true
  serial: 1
  tasks:
    - name: auto pass
      include_tasks: 'tasks/auto_pass/{{ linux_name }}.yml'

# rke Node에 etc_hosts 적용
- name: Set etc hosts
  hosts:
    - all
  tasks:
    - include: tasks/etc_hosts.yml
